version: 2
project_name: secretty

builds:
  - id: secretty
    main: ./cmd/secretty
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

release:
  github:
    owner: Suryansh-23
    name: secretty

brews:
  - name: secretty
    homepage: https://github.com/Suryansh-23/secretty
    description: macOS + Linux PTY wrapper that redacts secrets from terminal output
    license: MIT
    repository:
      owner: Suryansh-23
      name: homebrew-secretty
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    commit_author:
      name: secretty-bot
      email: noreply@github.com
    url_template: "https://github.com/Suryansh-23/secretty/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    caveats: |-
      SecreTTY may install shell hooks. Restart your shell to apply changes:
        exec $SHELL -l
      Or reload your shell config:
        source ~/.zshrc
        source ~/.bashrc
        source ~/.config/fish/config.fish

nfpms:
  - id: packages
    package_name: secretty
    builds:
      - secretty
    homepage: https://github.com/Suryansh-23/secretty
    maintainer: Suryansh-23 <noreply@github.com>
    description: macOS + Linux PTY wrapper that redacts secrets from terminal output
    license: MIT
    bindir: /usr/bin
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - deb
      - rpm
